// This file is NOT generated by Stainless. It tests the hand-maintained
// Idempotency-Key auto-mint patch. See .fernignore at the repo root.

package requestconfig

import (
	"context"
	"net/http"
	"net/http/httptest"
	"regexp"
	"strings"
	"sync/atomic"
	"testing"
)

var uuid4Re = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`)

func isValidUUID4(s string) bool { return uuid4Re.MatchString(s) }

// newTestConfig builds a RequestConfig pointed at a test server, mirroring how
// ExecuteNewRequest is invoked internally: a relative path plus a base URL.
func newTestConfig(t *testing.T, method, path string, srv *httptest.Server, opts ...RequestOption) *RequestConfig {
	t.Helper()
	allOpts := append([]RequestOption{WithDefaultBaseURL(srv.URL + "/")}, opts...)
	cfg, err := NewRequestConfig(context.Background(), method, path, nil, nil, allOpts...)
	if err != nil {
		t.Fatalf("NewRequestConfig: %v", err)
	}
	return cfg
}

// Test 1: POST to a send path with no Idempotency-Key -> server sees a valid UUID4.
func TestIdempotency_MintsOnSendPath(t *testing.T) {
	var got string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("Idempotency-Key")
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	cfg := newTestConfig(t, http.MethodPost, "v0/inboxes/inb_1/messages/send", srv)
	if err := cfg.Execute(); err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if !isValidUUID4(got) {
		t.Fatalf("expected a valid UUID4 Idempotency-Key, got %q", got)
	}
}

// Also exercise the other four send shapes end their path correctly.
func TestIdempotency_AllSendShapes(t *testing.T) {
	paths := []string{
		"v0/inboxes/inb_1/messages/send",
		"v0/inboxes/inb_1/messages/msg_1/reply",
		"v0/inboxes/inb_1/messages/msg_1/reply-all",
		"v0/inboxes/inb_1/messages/msg_1/forward",
		"v0/inboxes/inb_1/drafts/dft_1/send",
	}
	for _, p := range paths {
		t.Run(p, func(t *testing.T) {
			var got string
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				got = r.Header.Get("Idempotency-Key")
				w.WriteHeader(http.StatusOK)
			}))
			defer srv.Close()

			cfg := newTestConfig(t, http.MethodPost, p, srv)
			if err := cfg.Execute(); err != nil {
				t.Fatalf("Execute: %v", err)
			}
			if !isValidUUID4(got) {
				t.Fatalf("path %q: expected valid UUID4, got %q", p, got)
			}
		})
	}
}

// Test 2: a caller-set Idempotency-Key is preserved (case-insensitive match).
func TestIdempotency_CallerSetPreserved(t *testing.T) {
	const callerKey = "caller-supplied-key-123"
	var got string
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("Idempotency-Key")
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	// Set via a lowercased header name to prove case-insensitivity of the guard.
	setHeader := RequestOptionFunc(func(c *RequestConfig) error {
		c.Request.Header.Set("idempotency-key", callerKey)
		return nil
	})
	cfg := newTestConfig(t, http.MethodPost, "v0/inboxes/inb_1/messages/send", srv, setHeader)
	if err := cfg.Execute(); err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if got != callerKey {
		t.Fatalf("expected caller key %q preserved, got %q", callerKey, got)
	}
}

// Test 3: retry stability -> 503 once then 200; BOTH requests carry the IDENTICAL key.
func TestIdempotency_StableAcrossRetries(t *testing.T) {
	var keys []string
	var calls int32
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		keys = append(keys, r.Header.Get("Idempotency-Key"))
		if atomic.AddInt32(&calls, 1) == 1 {
			w.WriteHeader(http.StatusServiceUnavailable)
			return
		}
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	cfg := newTestConfig(t, http.MethodPost, "v0/inboxes/inb_1/messages/send", srv)
	if err := cfg.Execute(); err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if len(keys) != 2 {
		t.Fatalf("expected 2 attempts (503 then 200), got %d: %v", len(keys), keys)
	}
	if keys[0] == "" || !isValidUUID4(keys[0]) {
		t.Fatalf("attempt 1 key not a valid UUID4: %q", keys[0])
	}
	if keys[0] != keys[1] {
		t.Fatalf("expected identical key across retries, got %q and %q", keys[0], keys[1])
	}
}

// Test 4: a non-send POST gets NO injection.
func TestIdempotency_NonSendPostNoInjection(t *testing.T) {
	var got string
	var present bool
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got = r.Header.Get("Idempotency-Key")
		_, present = r.Header["Idempotency-Key"]
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	// Creating a draft is a POST but not a send.
	cfg := newTestConfig(t, http.MethodPost, "v0/inboxes/inb_1/drafts", srv)
	if err := cfg.Execute(); err != nil {
		t.Fatalf("Execute: %v", err)
	}
	if present || got != "" {
		t.Fatalf("expected no Idempotency-Key on non-send POST, got %q (present=%v)", got, present)
	}
}

// Test 5: two separate calls mint DIFFERENT keys.
func TestIdempotency_DistinctKeysPerCall(t *testing.T) {
	var mu = make(chan string, 2)
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		mu <- r.Header.Get("Idempotency-Key")
		w.WriteHeader(http.StatusOK)
	}))
	defer srv.Close()

	for i := 0; i < 2; i++ {
		cfg := newTestConfig(t, http.MethodPost, "v0/inboxes/inb_1/messages/send", srv)
		if err := cfg.Execute(); err != nil {
			t.Fatalf("Execute #%d: %v", i, err)
		}
	}
	k1, k2 := <-mu, <-mu
	if !isValidUUID4(k1) || !isValidUUID4(k2) {
		t.Fatalf("expected valid UUID4s, got %q and %q", k1, k2)
	}
	if k1 == k2 {
		t.Fatalf("expected distinct keys across separate calls, both were %q", k1)
	}
}

// Test 6: /messages/{id}/draft-reply (and the other draft-* variants) is NOT injected.
func TestIdempotency_DraftReplyNotInjected(t *testing.T) {
	notSend := []string{
		"v0/inboxes/inb_1/messages/msg_1/draft-reply",
		"v0/inboxes/inb_1/messages/msg_1/draft-reply-all",
		"v0/inboxes/inb_1/messages/msg_1/draft-forward",
	}
	for _, p := range notSend {
		t.Run(p, func(t *testing.T) {
			var present bool
			srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				_, present = r.Header["Idempotency-Key"]
				w.WriteHeader(http.StatusOK)
			}))
			defer srv.Close()

			cfg := newTestConfig(t, http.MethodPost, p, srv)
			if err := cfg.Execute(); err != nil {
				t.Fatalf("Execute: %v", err)
			}
			if present {
				t.Fatalf("path %q should NOT be injected but was", p)
			}
		})
	}
}

// Unit-level checks on the path matcher, including tricky lookalikes.
func TestIsSendPath(t *testing.T) {
	match := []string{
		"/v0/inboxes/x/messages/send",
		"/v0/inboxes/x/messages/msg_1/reply",
		"/v0/inboxes/x/messages/msg_1/reply-all",
		"/v0/inboxes/x/messages/msg_1/forward",
		"/v0/inboxes/x/drafts/d_1/send",
		"/v0/pods/p_1/drafts/d_1/send",
	}
	noMatch := []string{
		"/v0/inboxes/x/messages/msg_1/draft-reply",
		"/v0/inboxes/x/messages/msg_1/draft-reply-all",
		"/v0/inboxes/x/messages/msg_1/draft-forward",
		"/v0/inboxes/x/messages",
		"/v0/inboxes/x/messages/send/extra",
		"/v0/inboxes/x/drafts",
		"/v0/inboxes/x/messages/send/msg_1/reply", // send is not at the end
	}
	for _, p := range match {
		if !isSendPath(p) {
			t.Errorf("expected match for %q", p)
		}
	}
	for _, p := range noMatch {
		if isSendPath(p) {
			t.Errorf("expected NO match for %q", p)
		}
	}
	// A GET to a send path must not be treated as a send injection target;
	// the method guard handles that, but confirm the path predicate is only
	// consulted for the shapes we expect.
	if strings.HasSuffix("/v0/inboxes/x/messages/send", "/reply") {
		t.Fatal("sanity check failed")
	}
}
