// This file is NOT generated by Stainless. It is a hand-maintained patch that
// auto-mints an Idempotency-Key header for send endpoints so that all internal
// retries of a single logical call carry the SAME key. See .fernignore at the
// repo root for the list of files preserved across regeneration.

package requestconfig

import (
	"crypto/rand"
	"encoding/hex"
	"net/http"
	"regexp"
)

// idempotencyHeader is the header the AgentMail API uses to make sends
// idempotent. A retry with the same key returns the original message (and sends
// no second email); reuse with a different payload is a 409.
const idempotencyHeader = "Idempotency-Key"

// sendPathRegexp matches the path of the five POST send endpoints, anchored to
// the END of the URL path so it never matches the draft-* variants
// (/draft-reply, /draft-reply-all, /draft-forward). {segment} is a single path
// segment ([^/]+).
//
//	.../messages/send
//	.../messages/{segment}/reply
//	.../messages/{segment}/reply-all
//	.../messages/{segment}/forward
//	.../drafts/{segment}/send
var sendPathRegexp = regexp.MustCompile(`(?:/messages/send|/messages/[^/]+/(?:reply-all|reply|forward)|/drafts/[^/]+/send)$`)

// isSendPath reports whether path is one of the five send endpoints. This is the
// fast-path gate: it runs before any UUID minting so non-send requests stay
// zero-overhead.
func isSendPath(path string) bool {
	return sendPathRegexp.MatchString(path)
}

// maybeSetIdempotencyKey mints a UUID4 and sets it as the Idempotency-Key header
// when, and only when, the request is a POST to a send endpoint and the caller
// has not already supplied an Idempotency-Key header (matched case-insensitively
// via the canonicalized header key). It must be called BEFORE the retry loop so
// every cloned attempt inherits the same key.
func maybeSetIdempotencyKey(req *http.Request) {
	if req == nil || req.Method != http.MethodPost || req.URL == nil {
		return
	}
	if !isSendPath(req.URL.Path) {
		return
	}
	// http.Header.Get canonicalizes the key, so this is case-insensitive and
	// respects any Idempotency-Key the caller set explicitly.
	if req.Header.Get(idempotencyHeader) != "" {
		return
	}
	if key, err := newUUID4(); err == nil {
		req.Header.Set(idempotencyHeader, key)
	}
}

// newUUID4 returns a random RFC 4122 version-4 UUID in canonical
// 8-4-4-4-12 form. It uses crypto/rand so it adds no third-party dependency.
func newUUID4() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	// Set the version (4) and variant (RFC 4122) bits.
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80

	var buf [36]byte
	hex.Encode(buf[0:8], b[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], b[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], b[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], b[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:36], b[10:16])
	return string(buf[:]), nil
}
